# Generated by Django 2.1 on 2019-03-09 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('website', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('ad_type', models.CharField(max_length=20)),
                ('ad_shape', models.CharField(max_length=10)),
                ('alternate', models.CharField(max_length=20)),
                ('total_views', models.IntegerField(default=0)),
                ('total_click', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('link', models.CharField(max_length=500)),
                ('square_img', models.ImageField(upload_to='images/')),
                ('verticle_img', models.ImageField(upload_to='images/')),
                ('horizontal_img', models.ImageField(upload_to='images/')),
                ('duration', models.IntegerField()),
                ('total_views', models.IntegerField(default=0)),
                ('total_click', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('link', models.CharField(max_length=500)),
                ('content', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('total_views', models.IntegerField(default=0)),
                ('total_click', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
