# Generated by Django 2.1 on 2019-03-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0003_auto_20190316_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('imageAd', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imageAd', to='Ads.ImageAd')),
                ('textAd', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='textAd', to='Ads.TextAd')),
            ],
        ),
    ]
